import { useEffect, useMemo, useState } from 'react'
import type { Company, MarketData, SortKey } from './lib/types'
import Hero from './components/Hero'
import SummaryStats from './components/SummaryStats'
import Filters from './components/Filters'
import BucketSection from './components/BucketSection'

type LoadState =
  | { status: 'loading' }
  | { status: 'error'; message: string }
  | { status: 'ready'; data: MarketData }

export default function App() {
  const [state, setState] = useState<LoadState>({ status: 'loading' })
  const [sortKey, setSortKey] = useState<SortKey>('ytd')
  const [query, setQuery] = useState('')

  useEffect(() => {
    fetch('data/market.json', { cache: 'no-cache' })
      .then((r) => {
        if (!r.ok) throw new Error(`market.json returned ${r.status}`)
        return r.json()
      })
      .then((data: MarketData) => setState({ status: 'ready', data }))
      .catch((e) => setState({ status: 'error', message: String(e.message ?? e) }))
  }, [])

  const allCompanies = useMemo<Company[]>(() => {
    if (state.status !== 'ready') return []
    return Object.values(state.data.buckets).flatMap((b) => b.members)
  }, [state])

  if (state.status === 'loading') {
    return <Centered>Setting the type…</Centered>
  }

  if (state.status === 'error') {
    return (
      <Centered>
        <div className="max-w-md text-center">
          <p className="mb-2 font-serif text-lg font-semibold text-claret">
            Couldn’t load market data.
          </p>
          <p className="text-sm text-ink-soft">{state.message}</p>
          <p className="mt-4 text-xs text-ink-faint">
            The data file is generated by <code className="text-ink-soft">data/fetch.py</code> and
            published alongside the app. Running locally? Run the fetcher first.
          </p>
        </div>
      </Centered>
    )
  }

  const { data } = state

  return (
    <div className="min-h-screen">
      <Hero asOf={data.asOf} baselineDate={data.baselineDate} all={allCompanies} />
      <SummaryStats all={allCompanies} />

      <main className="mx-auto max-w-5xl px-4">
        <Filters sortKey={sortKey} setSortKey={setSortKey} query={query} setQuery={setQuery} />
        {Object.entries(data.buckets).map(([id, bucket], i) => (
          <BucketSection
            key={id}
            id={id}
            index={i}
            bucket={bucket}
            sortKey={sortKey}
            query={query}
          />
        ))}
      </main>

      <footer className="border-t border-rule">
        <div className="mx-auto max-w-5xl px-4 py-10 text-xs leading-relaxed text-ink-soft">
          <p className="max-w-3xl">
            Prices refresh hourly via Yahoo Finance — intraday during market hours, last close
            otherwise. Year-to-date is measured from the first 2026 trading close and is
            split-adjusted. Non-USD names show local-currency prices; percentage changes are
            currency-neutral. Not investment advice — a market-watching broadsheet, not a terminal.
          </p>
          <p className="tnum mt-3 uppercase tracking-[0.12em] text-ink-faint">
            Generated {data.generatedAt} · {allCompanies.length} names tracked
          </p>
        </div>
      </footer>
    </div>
  )
}

function Centered({ children }: { children: React.ReactNode }) {
  return (
    <div className="flex min-h-screen items-center justify-center px-4 font-serif text-ink-soft">
      {children}
    </div>
  )
}
